# Generated by Django 4.0 on 2021-12-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, verbose_name='author')),
                ('headline', models.CharField(max_length=120, verbose_name='headline')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('content', models.TextField(verbose_name='content')),
                ('city', models.CharField(max_length=120, verbose_name='city')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publish date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
