# Generated by Django 4.0 on 2021-12-12 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_created_at_alter_article_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='name')),
                ('last_name', models.CharField(max_length=120, verbose_name='surname')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='biography')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.PROTECT, to='news.reporter', verbose_name='author'),
        ),
    ]
